name: Test Package Install

on:
  workflow_dispatch:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_run:
    workflows: ["Build and Release"]
    types:
      - completed
    branches:
      - main

jobs:
  test-install:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' || github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: read

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@leomerl'

      - name: Create test directory
        run: |
          mkdir -p test-install
          cd test-install
          npm init -y

      - name: Create .npmrc in test directory
        working-directory: test-install
        run: |
          echo "@leomerl:registry=https://npm.pkg.github.com" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install package from GitHub Packages
        working-directory: test-install
        run: |
          npm install @leomerl/levys-awesome-mcp@latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify installation
        working-directory: test-install
        run: |
          # Check if package is installed
          npm list @leomerl/levys-awesome-mcp

          # Check if binaries are available
          npx levys-awesome-mcp --version || echo "Binary check: levys-awesome-mcp"
          npx agent-generator --help || echo "Binary check: agent-generator"
          npx agent-invoker --help || echo "Binary check: agent-invoker"
          npx build-executor --help || echo "Binary check: build-executor"
          npx content-writer --help || echo "Binary check: content-writer"

          # Check if the module can be imported
          node -e "const pkg = require('@leomerl/levys-awesome-mcp/package.json'); console.log('Package version:', pkg.version);"

      - name: Test basic functionality
        working-directory: test-install
        run: |
          # Create a simple test script
          cat > test.js << 'EOF'
          import('@leomerl/levys-awesome-mcp').then(module => {
            console.log('Package imported successfully');
            console.log('Available exports:', Object.keys(module));
          }).catch(err => {
            console.error('Failed to import package:', err);
            process.exit(1);
          });
          EOF

          # Run the test
          node test.js

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-install-results
          path: |
            test-install/package.json
            test-install/package-lock.json
            test-install/.npmrc