name: Verify NPM Install

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  verify-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Pack the package
        run: npm pack

      - name: Create test directory and install package
        run: |
          mkdir -p /tmp/test-install
          cd /tmp/test-install
          npm init -y
          npm install $GITHUB_WORKSPACE/leomerl-levys-awesome-mcp-*.tgz

      - name: Verify commands directory was created
        working-directory: /tmp/test-install
        run: |
          if [ ! -d ".claude/commands" ]; then
            echo "❌ ERROR: .claude/commands directory was not created after installation"
            exit 1
          fi
          echo "✅ SUCCESS: .claude/commands directory exists"

          # Also check if it contains any files
          FILE_COUNT=$(find .claude/commands -type f | wc -l)
          echo "Found ${FILE_COUNT} file(s) in .claude/commands"

          if [ "$FILE_COUNT" -eq 0 ]; then
            echo "⚠️  WARNING: .claude/commands directory is empty"
          else
            echo "✅ .claude/commands contains files:"
            ls -la .claude/commands
          fi

      - name: Verify agents directory was created
        working-directory: /tmp/test-install
        run: |
          if [ ! -d ".claude/agents" ]; then
            echo "❌ ERROR: .claude/agents directory was not created after installation"
            exit 1
          fi
          echo "✅ SUCCESS: .claude/agents directory exists"

          # Check if it contains any agent files
          AGENT_COUNT=$(find .claude/agents -type f -name "*.md" | wc -l)
          echo "Found ${AGENT_COUNT} agent file(s) in .claude/agents"

          if [ "$AGENT_COUNT" -eq 0 ]; then
            echo "❌ ERROR: .claude/agents directory contains no agent (.md) files"
            exit 1
          else
            echo "✅ .claude/agents contains ${AGENT_COUNT} agent(s):"
            ls -la .claude/agents
          fi
